name: pip_config
description: PIPIS-AFC configuration client.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
